#- id: infracost_breakdown
#  name: Infracost breakdown
#  description: Check terraform infrastructure cost
#  entry: hooks/infracost_breakdown.sh
#  language: script
#  require_serial: true
#  files: \.(tf(vars)?|hcl)$
#  exclude: \.terraform/.*$

- id: terraform_fmt
  name: Terraform fmt
  description: Rewrites all Terraform configuration files to a canonical format.
  entry: hooks/terraform_fmt.sh
  language: script
  files: (\.tf|\.tfvars)$
  exclude: \.terraform/.*$


- id: terraform_validate
  name: Terraform validate
  description: Validates all Terraform configuration files.
  require_serial: true
  entry: hooks/terraform_validate.sh
  language: script
  files: \.(tf(vars)?|terraform\.lock\.hcl)$
  exclude: \.terraform/.*$
